# Generated by Django 4.2.7 on 2025-09-28 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
        ("bookings", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermetrics",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="routemetrics",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to="core.route",
            ),
        ),
        migrations.AddField(
            model_name="performancealert",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="performancealert",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.route",
            ),
        ),
        migrations.AddField(
            model_name="performancealert",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.vehicle",
            ),
        ),
        migrations.AddIndex(
            model_name="dailymetrics",
            index=models.Index(fields=["date"], name="daily_metri_date_07dd2d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="dailymetrics",
            unique_together={("date",)},
        ),
        migrations.AddField(
            model_name="corporatemetrics",
            name="corporate_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to="core.corporateaccount",
            ),
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.route",
            ),
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.subscription",
            ),
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="usermetrics",
            index=models.Index(
                fields=["user", "date"], name="user_metric_user_id_fc2016_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usermetrics",
            index=models.Index(
                fields=["date", "total_spent"], name="user_metric_date_5a01bc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usermetrics",
            unique_together={("user", "date")},
        ),
        migrations.AddIndex(
            model_name="routemetrics",
            index=models.Index(
                fields=["route", "date"], name="route_metri_route_i_38de10_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routemetrics",
            index=models.Index(
                fields=["date", "capacity_utilization"],
                name="route_metri_date_71168f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routemetrics",
            unique_together={("route", "date")},
        ),
        migrations.AddIndex(
            model_name="performancealert",
            index=models.Index(
                fields=["alert_type", "severity"], name="performance_alert_t_4db7f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performancealert",
            index=models.Index(
                fields=["resolved", "created_at"], name="performance_resolve_4ccdca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="corporatemetrics",
            index=models.Index(
                fields=["corporate_account", "date"],
                name="corporate_m_corpora_6fe8a7_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="corporatemetrics",
            unique_together={("corporate_account", "date")},
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["event_type", "timestamp"],
                name="analytics_e_event_t_5b2eb4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["user", "timestamp"], name="analytics_e_user_id_4d513c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["session_id"], name="analytics_e_session_b3cbf5_idx"
            ),
        ),
    ]
