# Generated by Django 4.2.7 on 2025-09-28 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0002_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("BOOKING_CONFIRMATION", "Booking Confirmation"),
                            ("BOOKING_REMINDER", "Booking Reminder"),
                            ("BOOKING_CANCELLATION", "Booking Cancellation"),
                            ("ROUTE_DELAY", "Route Delay"),
                            ("ROUTE_CANCELLATION", "Route Cancellation"),
                            ("PAYMENT_SUCCESS", "Payment Success"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("SUBSCRIPTION_RENEWAL", "Subscription Renewal"),
                            ("SUBSCRIPTION_EXPIRED", "Subscription Expired"),
                            ("PROMOTION", "Promotion"),
                            ("SYSTEM_UPDATE", "System Update"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("PUSH", "Push Notification"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("IN_APP", "In-App"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title_template", models.CharField(max_length=255)),
                ("message_template", models.TextField()),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Documentation of available template variables",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "db_table": "notification_templates",
                "unique_together": {("notification_type", "channel")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("BOOKING_CONFIRMATION", "Booking Confirmation"),
                            ("BOOKING_REMINDER", "Booking Reminder"),
                            ("BOOKING_CANCELLATION", "Booking Cancellation"),
                            ("ROUTE_DELAY", "Route Delay"),
                            ("ROUTE_CANCELLATION", "Route Cancellation"),
                            ("PAYMENT_SUCCESS", "Payment Success"),
                            ("PAYMENT_FAILED", "Payment Failed"),
                            ("SUBSCRIPTION_RENEWAL", "Subscription Renewal"),
                            ("SUBSCRIPTION_EXPIRED", "Subscription Expired"),
                            ("PROMOTION", "Promotion"),
                            ("SYSTEM_UPDATE", "System Update"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("PUSH", "Push Notification"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("IN_APP", "In-App"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("READ", "Read"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "external_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bookings.booking",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payments.payment",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notifications",
                "indexes": [
                    models.Index(
                        fields=["user", "status", "created_at"],
                        name="notificatio_user_id_286b90_idx",
                    ),
                    models.Index(
                        fields=["notification_type", "channel"],
                        name="notificatio_notific_1897f3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=255)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("IOS", "iOS"),
                            ("ANDROID", "Android"),
                            ("WEB", "Web"),
                        ],
                        max_length=10,
                    ),
                ),
                ("device_id", models.CharField(blank=True, max_length=255, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Token",
                "verbose_name_plural": "Device Tokens",
                "db_table": "device_tokens",
                "indexes": [
                    models.Index(
                        fields=["user", "platform"],
                        name="device_toke_user_id_af4827_idx",
                    ),
                    models.Index(
                        fields=["active", "platform"],
                        name="device_toke_active_c377b0_idx",
                    ),
                ],
                "unique_together": {("user", "token")},
            },
        ),
    ]
